apiVersion: apps/v1
kind: Deployment
metadata:
  name: anacart-deployment
  labels:
    app: anacart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anacart
  template:
    metadata:
      labels:
        app: anacart
    spec:
      containers:
      - name: anacart
        image: ganesharavind124/anacart:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: anacartservice
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32765
